const GAME_INITIAL = 'GAME_INITIAL';
const GAME_STARTED = 'GAME_STARTED';
const GAME_FINISHED = 'GAME_FINISHED';

const CARD_OPENED = 'CARD_OPENED';
const CARD_CLOSED = 'CARD_CLOSED';
const CARD_DELETED = 'CARD_DELETED';

export {
  GAME_INITIAL,
  GAME_STARTED,
  GAME_FINISHED,
  CARD_OPENED,
  CARD_CLOSED,
  CARD_DELETED,
};
